// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: e2_api.proto

#ifndef PROTOBUF_e2_5fapi_2eproto__INCLUDED
#define PROTOBUF_e2_5fapi_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3000000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3000000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/generated_enum_reflection.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

namespace E2 {

// Internal implementation detail -- do not call these.
void protobuf_AddDesc_e2_5fapi_2eproto();
void protobuf_AssignDesc_e2_5fapi_2eproto();
void protobuf_ShutdownFile_e2_5fapi_2eproto();

class ConfigurationReply;
class ConfigurationRequest;

enum ReturnCode {
  SUCCESS = 0,
  UNKNOWN_ERROR = 1,
  ReturnCode_INT_MIN_SENTINEL_DO_NOT_USE_ = ::google::protobuf::kint32min,
  ReturnCode_INT_MAX_SENTINEL_DO_NOT_USE_ = ::google::protobuf::kint32max
};
bool ReturnCode_IsValid(int value);
const ReturnCode ReturnCode_MIN = SUCCESS;
const ReturnCode ReturnCode_MAX = UNKNOWN_ERROR;
const int ReturnCode_ARRAYSIZE = ReturnCode_MAX + 1;

const ::google::protobuf::EnumDescriptor* ReturnCode_descriptor();
inline const ::std::string& ReturnCode_Name(ReturnCode value) {
  return ::google::protobuf::internal::NameOfEnum(
    ReturnCode_descriptor(), value);
}
inline bool ReturnCode_Parse(
    const ::std::string& name, ReturnCode* value) {
  return ::google::protobuf::internal::ParseNamedEnum<ReturnCode>(
    ReturnCode_descriptor(), name, value);
}
// ===================================================================

class ConfigurationRequest : public ::google::protobuf::Message {
 public:
  ConfigurationRequest();
  virtual ~ConfigurationRequest();

  ConfigurationRequest(const ConfigurationRequest& from);

  inline ConfigurationRequest& operator=(const ConfigurationRequest& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const ConfigurationRequest& default_instance();

  void Swap(ConfigurationRequest* other);

  // implements Message ----------------------------------------------

  inline ConfigurationRequest* New() const { return New(NULL); }

  ConfigurationRequest* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const ConfigurationRequest& from);
  void MergeFrom(const ConfigurationRequest& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(ConfigurationRequest* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional string name = 1;
  void clear_name();
  static const int kNameFieldNumber = 1;
  const ::std::string& name() const;
  void set_name(const ::std::string& value);
  void set_name(const char* value);
  void set_name(const char* value, size_t size);
  ::std::string* mutable_name();
  ::std::string* release_name();
  void set_allocated_name(::std::string* name);

  // optional string mgmt_ip = 2;
  void clear_mgmt_ip();
  static const int kMgmtIpFieldNumber = 2;
  const ::std::string& mgmt_ip() const;
  void set_mgmt_ip(const ::std::string& value);
  void set_mgmt_ip(const char* value);
  void set_mgmt_ip(const char* value, size_t size);
  ::std::string* mutable_mgmt_ip();
  ::std::string* release_mgmt_ip();
  void set_allocated_mgmt_ip(::std::string* mgmt_ip);

  // @@protoc_insertion_point(class_scope:E2.ConfigurationRequest)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  bool _is_default_instance_;
  ::google::protobuf::internal::ArenaStringPtr name_;
  ::google::protobuf::internal::ArenaStringPtr mgmt_ip_;
  mutable int _cached_size_;
  friend void  protobuf_AddDesc_e2_5fapi_2eproto();
  friend void protobuf_AssignDesc_e2_5fapi_2eproto();
  friend void protobuf_ShutdownFile_e2_5fapi_2eproto();

  void InitAsDefaultInstance();
  static ConfigurationRequest* default_instance_;
};
// -------------------------------------------------------------------

class ConfigurationReply : public ::google::protobuf::Message {
 public:
  ConfigurationReply();
  virtual ~ConfigurationReply();

  ConfigurationReply(const ConfigurationReply& from);

  inline ConfigurationReply& operator=(const ConfigurationReply& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const ConfigurationReply& default_instance();

  void Swap(ConfigurationReply* other);

  // implements Message ----------------------------------------------

  inline ConfigurationReply* New() const { return New(NULL); }

  ConfigurationReply* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const ConfigurationReply& from);
  void MergeFrom(const ConfigurationReply& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(ConfigurationReply* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional .E2.ReturnCode code = 1;
  void clear_code();
  static const int kCodeFieldNumber = 1;
  ::E2::ReturnCode code() const;
  void set_code(::E2::ReturnCode value);

  // optional string code_str = 2;
  void clear_code_str();
  static const int kCodeStrFieldNumber = 2;
  const ::std::string& code_str() const;
  void set_code_str(const ::std::string& value);
  void set_code_str(const char* value);
  void set_code_str(const char* value, size_t size);
  ::std::string* mutable_code_str();
  ::std::string* release_code_str();
  void set_allocated_code_str(::std::string* code_str);

  // @@protoc_insertion_point(class_scope:E2.ConfigurationReply)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  bool _is_default_instance_;
  ::google::protobuf::internal::ArenaStringPtr code_str_;
  int code_;
  mutable int _cached_size_;
  friend void  protobuf_AddDesc_e2_5fapi_2eproto();
  friend void protobuf_AssignDesc_e2_5fapi_2eproto();
  friend void protobuf_ShutdownFile_e2_5fapi_2eproto();

  void InitAsDefaultInstance();
  static ConfigurationReply* default_instance_;
};
// ===================================================================


// ===================================================================

#if !PROTOBUF_INLINE_NOT_IN_HEADERS
// ConfigurationRequest

// optional string name = 1;
inline void ConfigurationRequest::clear_name() {
  name_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& ConfigurationRequest::name() const {
  // @@protoc_insertion_point(field_get:E2.ConfigurationRequest.name)
  return name_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void ConfigurationRequest::set_name(const ::std::string& value) {
  
  name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:E2.ConfigurationRequest.name)
}
inline void ConfigurationRequest::set_name(const char* value) {
  
  name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:E2.ConfigurationRequest.name)
}
inline void ConfigurationRequest::set_name(const char* value, size_t size) {
  
  name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:E2.ConfigurationRequest.name)
}
inline ::std::string* ConfigurationRequest::mutable_name() {
  
  // @@protoc_insertion_point(field_mutable:E2.ConfigurationRequest.name)
  return name_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* ConfigurationRequest::release_name() {
  
  return name_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void ConfigurationRequest::set_allocated_name(::std::string* name) {
  if (name != NULL) {
    
  } else {
    
  }
  name_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), name);
  // @@protoc_insertion_point(field_set_allocated:E2.ConfigurationRequest.name)
}

// optional string mgmt_ip = 2;
inline void ConfigurationRequest::clear_mgmt_ip() {
  mgmt_ip_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& ConfigurationRequest::mgmt_ip() const {
  // @@protoc_insertion_point(field_get:E2.ConfigurationRequest.mgmt_ip)
  return mgmt_ip_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void ConfigurationRequest::set_mgmt_ip(const ::std::string& value) {
  
  mgmt_ip_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:E2.ConfigurationRequest.mgmt_ip)
}
inline void ConfigurationRequest::set_mgmt_ip(const char* value) {
  
  mgmt_ip_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:E2.ConfigurationRequest.mgmt_ip)
}
inline void ConfigurationRequest::set_mgmt_ip(const char* value, size_t size) {
  
  mgmt_ip_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:E2.ConfigurationRequest.mgmt_ip)
}
inline ::std::string* ConfigurationRequest::mutable_mgmt_ip() {
  
  // @@protoc_insertion_point(field_mutable:E2.ConfigurationRequest.mgmt_ip)
  return mgmt_ip_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* ConfigurationRequest::release_mgmt_ip() {
  
  return mgmt_ip_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void ConfigurationRequest::set_allocated_mgmt_ip(::std::string* mgmt_ip) {
  if (mgmt_ip != NULL) {
    
  } else {
    
  }
  mgmt_ip_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), mgmt_ip);
  // @@protoc_insertion_point(field_set_allocated:E2.ConfigurationRequest.mgmt_ip)
}

// -------------------------------------------------------------------

// ConfigurationReply

// optional .E2.ReturnCode code = 1;
inline void ConfigurationReply::clear_code() {
  code_ = 0;
}
inline ::E2::ReturnCode ConfigurationReply::code() const {
  // @@protoc_insertion_point(field_get:E2.ConfigurationReply.code)
  return static_cast< ::E2::ReturnCode >(code_);
}
inline void ConfigurationReply::set_code(::E2::ReturnCode value) {
  
  code_ = value;
  // @@protoc_insertion_point(field_set:E2.ConfigurationReply.code)
}

// optional string code_str = 2;
inline void ConfigurationReply::clear_code_str() {
  code_str_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& ConfigurationReply::code_str() const {
  // @@protoc_insertion_point(field_get:E2.ConfigurationReply.code_str)
  return code_str_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void ConfigurationReply::set_code_str(const ::std::string& value) {
  
  code_str_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:E2.ConfigurationReply.code_str)
}
inline void ConfigurationReply::set_code_str(const char* value) {
  
  code_str_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:E2.ConfigurationReply.code_str)
}
inline void ConfigurationReply::set_code_str(const char* value, size_t size) {
  
  code_str_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:E2.ConfigurationReply.code_str)
}
inline ::std::string* ConfigurationReply::mutable_code_str() {
  
  // @@protoc_insertion_point(field_mutable:E2.ConfigurationReply.code_str)
  return code_str_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* ConfigurationReply::release_code_str() {
  
  return code_str_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void ConfigurationReply::set_allocated_code_str(::std::string* code_str) {
  if (code_str != NULL) {
    
  } else {
    
  }
  code_str_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), code_str);
  // @@protoc_insertion_point(field_set_allocated:E2.ConfigurationReply.code_str)
}

#endif  // !PROTOBUF_INLINE_NOT_IN_HEADERS
// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace E2

#ifndef SWIG
namespace google {
namespace protobuf {

template <> struct is_proto_enum< ::E2::ReturnCode> : ::google::protobuf::internal::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::E2::ReturnCode>() {
  return ::E2::ReturnCode_descriptor();
}

}  // namespace protobuf
}  // namespace google
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_e2_5fapi_2eproto__INCLUDED
